language: python
script:
  - pytest
deploy:
  provider: heroku
  api_key:
    secure: "o4GG4yUGhvKTTibz2Czp3T2wRxM5Y6rrYnJwGJ5lEqeIDlvD6NTIq6mOwYvd7qwgN9GPGHtCD8kwNs1ubZ5isds2ci8FvFQIUFnKbtj46ppmfmAr1D2FUhAMkvS1DpS18VYvipdP/OM/hzMZR0eabtGbBuMdxzA1yeFMq0wNMGhq8a6kMQb1jxsxqoX/q2Yev1oSc/kqhK/M0VvSmo+at0otUZA9n6R5IuDT9MKHGehmYLNRdo5IiOysutj0z+4YvZqtd9NqtyeMMD3nbhr07F/K3inclFpDLFlqUmpb08hfkTejtX4ZfFCt32CrCp9ws8RjuxsqOhkI65tp6BdbRAeW67F3PApisRyXtmQUtKjRcVRLIDdv1hE1wkrxGp3jU1a2/NPOwOncyVhLTLaLrvki0fWPpjtduQN0UUPwi/kfyjJQw6zKZ6uZ+ifZ8Gp83b6QCYn1N2v5px79VXNTQJaQPyaFgsEEZZ6GrOl0KtifGtznnWL0uh/gypcINmazJAJrs4ru62suHmNA6QwXr3YWeQvDmmFE7irwweKWKgxKs+9zoftAc00BrLDsb1FVEGlFYyxkOxa+4gEdMZs86GVuM3mt7YezEA5ghuah/j5fVFtw3mlSzF/Twxl9LEmDNq6NxPG2fyhdTNpCF70H4L9VhiO5GOo7+ViiLPvt5IA=
"  
