# Generated by Django 3.0.6 on 2020-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=50),
        ),
    ]
