# Generated by Django 3.0.6 on 2020-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_auto_20200718_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=50),
        ),
    ]
