# Generated by Django 3.0.6 on 2020-07-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrating', '0002_auto_20200701_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='take_again',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')]),
        ),
    ]
