# Generated by Django 3.0.6 on 2020-07-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixing_rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('liveable_cond', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(max_length=1000)),
                ('take_again', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')])),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.Landlord')),
            ],
        ),
    ]
