# Generated by Django 3.0.6 on 2020-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='take_again',
            field=models.BooleanField(choices=[('No', False), ('Yes', True)]),
        ),
    ]
